services:
  app1:
    image: demo-spring
    ports:
      - 8081:8080
    environment:
      - SERVER_NAME=app1
  app2:
    image: demo-spring
    ports:
      - 8082:8080
    environment:
      - SERVER_NAME=app2
  nginx:
    build: ./Nginx
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
