services:
  app1: 
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - SERVER_NAME=app1
  app2:
    build:
      context: .
    ports:
      - 8082:8080
    environment:
      - SERVER_NAME=app2