services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  app1:
    image: demo-spring
    ports:
      - 8081:8080
    environment:
      - SERVER_NAME=app1
      - DATABASE_PASSWORD=example
      - DATABASE_HOST=db
    depends_on:
      - db
  app2:
    image: demo-spring
    ports:
      - 8082:8080
    environment:
      - SERVER_NAME=app2
      - DATABASE_PASSWORD=example
      - DATABASE_HOST=db
    depends_on:
      - db
  nginx:
    build: ./Nginx
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
