spring:
  datasource:
    url: "jdbc:postgresql://${HOST:localhost}:5432/postgres"
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  name: ${SERVER_NAME:default}