spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:5432/postgres"
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  name: ${SERVER_NAME:default}